project:
  type: website
  output-dir: docs

website:
  title: "Cash Looi"
  navbar:
    left:
      - href: index.qmd
       # text: Home
     # - about.qmd
      #- conference.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

