project:
  type: website
  output-dir: docs
  resources: 
    - docs
    - styles.scss

website:
  title: "Cash Looi"
  navbar:
    background: primary
    #left:
     # - href: index.qmd    

body-footer: | 
  Copyright:  Cash Looi, 2026

date-format: "D MMMM YYYY"

format:
  html:
  
    toc: false
    css: styles.css
    page-layout: full