project:
  type: website
  output-dir: docs

website:

  title: "Cash Looi"
  navbar:
    left:
      - href: index.qmd
       # text: Home
     # - about.qmd
      #- conference.qmd
=======
  title: "Cash Looi"   # this becomes the "Home" link
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: conference.qmd
        text: Conference
>>>>>>> d18df6dc8c7ec9cac5db521c878754ae63e9f3c0

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

